version: '3.8'

services:
  app:
    build:
      context: .  # Use the current directory for the build
    ports:
      - "3000:3000"  # Expose port 3000 on both host and container
    volumes:
      - ./prisma:/app/prisma  # Mount the prisma folder for the SQLite database and schema
    env_file:
      - ./.env  # Load environment variables from the .env file
    command: npm run start  # Start the Next.js server in dev mode when the container is up



